force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Employee.cls
public class Employee {

public pageReference doSave() {
upsert emp;
return new pageReference('https://www.google.com/');
}
  Employee__c  emp;
public Employee() {
id i = apexpages.currentpage().getparameters().get('id');
if(i == null){
emp = new Employee__c();
}else{

emp = [select First_Name__c, Last_Name__c,  Address__c,  Phone_Number__c from Employee__c where  id = :i];
}
}
public Employee__c getEmployee(){
return emp;
}
}