force-app/main/default/objects/BirlasoftEmployee__c/BirlasoftEmployee__c.object-meta.xml
<CustomObject>
    <label>BirlasoftEmployee</label>
    <nameField>
        <label>BirlasoftEmployee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BirlasoftEmployees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BirlasoftEmployee__c/fields/Emp_Departement__c.field-meta.xml
<CustomField>
    <fullName>Emp_Departement__c</fullName>
    <label>Emp Departement</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BirlasoftEmployee__c/fields/Emp_Salary__c.field-meta.xml
<CustomField>
    <fullName>Emp_Salary__c</fullName>
    <label>Emp Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BirlasoftEmployee__c/fields/EmpAddress__c.field-meta.xml
<CustomField>
    <fullName>EmpAddress__c</fullName>
    <label>EmpAddress</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BirlasoftEmployee__c/fields/Father_Name__c.field-meta.xml
<CustomField>
    <fullName>Father_Name__c</fullName>
    <label>Father Name</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BirlasoftEmployee.cls
public class BirlasoftEmployee {
    
    @AuraEnabled
    public static void insertBslEmp(string enm, string efnm, string eadr, string edept, integer esalary) {
        
        BirlasoftEmployee__c Bempl = new BirlasoftEmployee__c();
        Bempl.name = enm;
        Bempl.Father_Name__c = efnm;
        Bempl.EmpAddress__c = eadr;
        Bempl.Emp_Departement__c = edept;
        Bempl.Emp_Salary__c = esalary;
        insert Bempl;
    }

}